# Generated by Django 4.2.10 on 2024-02-28 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_delivery_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerDetails',
            new_name='customer_details',
        ),
    ]
